### ISSUE TITLE
Compilation errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [ebruck/radiotray-ng#100]
Compilation errors on Ubuntu 14.04:
https://travis-ci.com/probonopd/radiotray-ng/builds/97130454

How to compile on Ubuntu 14.04?

**Comment by ebruck** [comment]
It looks like the jsoncpp library is too old. I've had fun in the past with Travis and its default 14.04 environment. We ended up having to download libjsoncpp and build it ourselves. 

I wouldn't bother with 14.04 as it will be EOL in April. I'd also avoid building against such an old gstreamer version and libs.

**Comment by probonopd** [comment]
So what is the oldest one if is known to build on without hassle?

**Comment by ebruck** [comment]
I wouldn't use anything older than 1.7.4.

**Comment by probonopd** [comment]
This would exclude all Ubuntu releases prior to bionic, according to [here](https://packages.ubuntu.com/bionic/libjsoncpp-dev).

**Comment by ebruck** [comment]
Well it does build fine on 16.04 which is no where near bleeding edge.

**Comment by probonopd** [comment]
So there will be no way to build master on 14.04, the currently oldest still-supported Ubuntu release?

**Comment by ebruck** [comment]
I'm certainly not going to put effort into a release that will be EOL in April. I've never supported that version of Ubuntu. It's just too old without updating the compiler for C++14 support and jsoncpp which has newer and better functionality I wanted.

**Comment by ebruck** [comment]
If you want to fork and make it work for yourself then have a look at my solution for another project: https://github.com/bluzelle/swarmDB/blob/devel/cmake/jsoncpp.cmake

**Comment by probonopd** [comment]
Thanks for the clarification.

**Comment by probonopd** [comment]
On Ubutnu 16.04 I am also getting compilation errors:
https://travis-ci.com/probonopd/radiotray-ng/builds/97594727

**Comment by ebruck** [comment]
Try **not** updating the compiler. There looks to be an issue in the newer one not knowing that certain headers are from the "system" and that it should ignore any warnings.

I'm using this from a very old install with no problems: 

> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)  with no problems.

**Comment by probonopd** [comment]
That works for me. Thanks.
